[package]
name = "embedded-layout"
version = "0.1.0"
license = "MIT"
description = "Extend embedded-graphics with simple layout functions"
repository = "https://github.com/bugadani/embedded-layout"
authors = ["Dániel Buga <bugadani@gmail.com>"]
keywords = ["embedded-graphics", "layout", "linear-layout"]
categories = ["no-std", "embedded", "graphics"]
edition = "2018"

exclude = [
    ".gitignore",
    ".github/",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.7.0-alpha.3"

[dev-dependencies]
embedded-graphics-simulator = "0.3.0-alpha.2"
